"""add user_id column

Revision ID: 86f795f40959
Revises: dad095af1578
Create Date: 2026-02-13 20:03:30.202549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f795f40959'
down_revision: Union[str, Sequence[str], None] = 'dad095af1578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_bets_user_id'), 'bets', ['user_id'], unique=False)
    op.create_foreign_key(None, 'bets', 'users', ['user_id'], ['id'], referent_schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bets', type_='foreignkey')
    op.drop_index(op.f('ix_bets_user_id'), table_name='bets')
    op.drop_column('bets', 'user_id')
    # ### end Alembic commands ###
