"""Initial clean migration

Revision ID: dad095af1578
Revises: 
Create Date: 2026-01-16 20:11:18.465915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dad095af1578'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('home_team', sa.String(length=80), nullable=False),
    sa.Column('away_team', sa.String(length=80), nullable=False),
    sa.Column('market_type', sa.Enum('MATCH_RESULT', 'HANDICAP', 'CORNERS', 'CARDS', 'PLAYER_SHOTS', 'GOALS', 'PLAYER_SHOTS_TARGET', 'PLAYER_GOALS', name='market_type', native_enum=False), nullable=False),
    sa.Column('target_scope', sa.Enum('MATCH', 'HOME_TEAM', 'AWAY_TEAM', name='target_scope', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'WON', 'LOST', 'VOID', name='status', native_enum=False), nullable=False),
    sa.Column('selection', sa.String(length=120), nullable=False),
    sa.Column('selection_details', sa.String(length=120), nullable=True),
    sa.Column('line', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('odds', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('stake', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('potential_payout', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('net_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bets_market_type'), 'bets', ['market_type'], unique=False)
    op.create_index(op.f('ix_bets_status'), 'bets', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bets_status'), table_name='bets')
    op.drop_index(op.f('ix_bets_market_type'), table_name='bets')
    op.drop_table('bets')
    # ### end Alembic commands ###
